### ISSUE TITLE
Update to newest ionic beta

### ISSUE THREAD

**Issue by alexmgrant** [domenukk/ionic2-meteor#1]
Hey mate, 

This is broken with any ionic beta version above 2 I believe. Ionic changed their package name to ìonic-angular`from`ionic-framework`. I'm trying to fix it, but I'm a node noob and having trouble getting the make file to run and compile with the new ionic package name.

**Comment by domenukk** [comment]
Sorry I'm not super supporting this project right now as https://atmospherejs.com/barbatus/ionic2-meteor came out shortly after I did this and worked pretty well for my needs. It appears not to be beta >2 either but that may be more easy to fix :)

**Comment by alexmgrant** [comment]
Sorry for the late response. All good. Thank you.
